version: '3'
services:
  mysql:
    container_name: shuttle-mysql
    image: mysql:1
    build: ./mysql
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${dbPassword}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: shuttle-redis
    image: redis
    command: redis-server --requirepass ${redisPassword}
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shuttle-rabbitmq
    hostname: rabbitmq
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${mqUser}
      RABBITMQ_DEFAULT_PASS: ${mqPassword}
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms218m -Xmx218m" #设置使用jvm内存大小
    volumes:
      - /elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300

  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - ${port}:${port}
    links:
      - elasticsearch:es
    environment:
      dbHost: mysql
      dbName: ${dbName}
      dbUser: ${dbUser}
      dbPasswd: ${dbPassword}
      key: ${key}
      appId: ${appId}
      gateway: ${gateway}
      notifyUrl: ${notifyUrl}
      redisPassword: ${redisPassword}
      redisHost: redis
      mqHost: rabbitmq
      mqUser: ${mqUser}
      mqPasswd: ${mqPassword}
      redirectUrl: ${redirectUrl}
      returnUrl: ${returnUrl}
      druidUser: ${druidUser}
      druidPasswd: ${druidPasswd}
      port: ${port}
      elasticsearchUrl: http://es:9200
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
      - redis
      - rabbitmq